FROM debian:latest

WORKDIR /app

# Install dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    sudo curl ffmpeg git locales nano \
    python3 python3-pip screen ssh unzip wget

# Configure locale
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# SSH setup with persistent keys
RUN mkdir -p /run/sshd && \
    ssh-keygen -A && \
    mkdir -p /root/.ssh && \
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFshKeW/SRrfepjUPfA8LfZRg3sqX4rKhrSXB5w6K1Li Generated By Termius' > /root/.ssh/authorized_keys && \
    chmod 700 /root/.ssh && \
    chmod 600 /root/.ssh/authorized_keys && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'root:choco' | chpasswd

# Web content
RUN mkdir -p /app/www && \
    echo "<!doctype html><html><body><h1>MyApp Web Server</h1><p>Served via myapp-web.serveo.net</p></body></html>" > /app/www/index.html

# Custom server with health check
RUN echo 'from http.server import SimpleHTTPRequestHandler; from http import server\n\
class CustomHandler(SimpleHTTPRequestHandler):\n\
    def do_GET(self):\n\
        if self.path == "/health":\n\
            self.send_response(200)\n\
            self.end_headers()\n\
            self.wfile.write(b"OK")\n\
        else:\n\
            super().do_GET()\n\
server.test(HandlerClass=CustomHandler, port=8000, directory="/app/www")' > /app/server.py

# Startup script with guaranteed subdomain
RUN echo "#!/bin/sh\n\
# Generate SSH key if missing (for subdomain ownership)\n\
if [ ! -f /root/.ssh/id_ed25519 ]; then\n\
    ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ''\n\
fi\n\n\
# Start Python server\n\
python3 /app/server.py &\n\n\
# Start SSH tunnel with fixed subdomain\n\
while true; do\n\
  echo 'Starting tunnel with subdomain myapp-web...'\n\
  ssh -i /root/.ssh/id_ed25519 -N \\\n\
      -o StrictHostKeyChecking=no \\\n\
      -o ServerAliveInterval=60 \\\n\
      -o ExitOnForwardFailure=yes \\\n\
      -R myapp-web:80:localhost:8000 \\\n\
      serveo.net\n\
  sleep 10\ndone &\n\n\
# Start SSH server\n\
/usr/sbin/sshd -D" > /start && \
    chmod +x /start

EXPOSE 8000

CMD ["/bin/sh", "/start"]
